import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
export async function runRosterChecks({client,engine,root,uid,outsider,rpc,read,check,reject}) {
 const upgrade=await fs.readFile(path.join(root,'migrations/character-v2/character-roster.sql'),'utf8');
 await client.query(upgrade);
 const roster=async(op='list',id=null,reserved=null)=>(await client.query('select public.df_character_roster($1,$2,$3,$4) result',['TEST',op,id,reserved])).rows[0].result;
 const setUser=async user=>client.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);
 await setUser(uid);
 await client.query("insert into public.room_members(room_code,user_id) values('TEST',$1)",[outsider]);
 const generated=async name=>(await rpc('personnages','insert',{}, {user_id:uid,nom:name,player_name:'MJ',intelligence:16,force:12,constitution:12,taille:12,pouvoir:12,dexterite:12,charisme:12})).rows[0].character_id;
 const preset=await generated('Roster preset');
 check((await roster()).characters.some(c=>c.character_id===preset && c.needs_sheet),'Generated PJ explicitly listed without fabricated campaign sheet');
 await roster('attach',preset);
 let row=(await rpc('pj_sheets','read',{character_id:preset},null)).rows[0];
 check(row.sheet_data.creation.phase==='draft' && row.sheet_data.stats.intelligence===16,'Explicit attach retains generated stats and creates draft');
 const state=row.id;
 const stats=JSON.stringify(row.sheet_data.stats);
 await roster('preset',preset,outsider);
 await roster('withdraw',preset);
 await setUser(outsider);
 await reject(roster('select',preset),'42501');
 await reject(roster('offer',preset),'42501');
 await reject(roster('dead',preset),'42501');
 await setUser(uid); await roster('offer',preset);
 await setUser(outsider);
 check((await roster()).characters.some(c=>c.character_id===preset && c.can_select),'Reserved preset is offered to its intended member');
 await roster('select',preset);
 row=(await rpc('pj_sheets','read',{user_id:outsider},null)).rows[0];
 check(row.id===state && JSON.stringify(row.sheet_data.stats)===stats,'Attribution retains permanent state and generated values');
 check((await roster()).selected_character_id===preset,'Selection is persisted on server');
 const originalRevision=row.revision;
 await roster('select',preset);
 check((await read(state)).revision===originalRevision,'Reselecting cannot refill XP or revise sheet');
 const other=await setUser(uid).then(()=>generated('Roster owner only'));
 await roster('attach',other);
 const twin=randomUUID();
 await client.query("insert into diceforge_v2.characters(id,owner_user_id,name,source_player_name,status,initial_record) values($1,$2,'Roster owner only','MJ','active','{\"intelligence\":19,\"force\":12}')",[twin,uid]);
 await roster('attach',twin);
 const originalOwnerSheet=(await rpc('pj_sheets','read',{character_id:other},null)).rows[0];
 const twinSheet=(await rpc('pj_sheets','read',{character_id:twin},null)).rows[0];
 check(originalOwnerSheet.id!==twinSheet.id && twinSheet.sheet_data.stats.intelligence===19,'Same-name PJ attach by identity, preserving each generation');
 await roster('select',twin);
 await rpc('personnages','update',{character_id:twin},{user_id:uid,nom:'Roster owner only',force:14});
 check((await read(originalOwnerSheet.id)).sheet_data.stats.force===12 && (await read(twinSheet.id)).sheet_data.stats.force===14,'Generator updates the selected identity even when names are equal');
 check((await rpc('pj_sheets','read',{user_id:uid},null)).rows[0].id===twinSheet.id,'Server selection narrows own implicit reads');
 await roster('new');
 check((await rpc('personnages','read',{user_id:uid},null)).rows.length===0,'New-character mode cannot silently load an existing PJ');
 const fresh=await generated('Roster fresh generation');await roster('attach',fresh);
 check((await roster()).selected_character_id===fresh,'Explicitly created campaign sheet becomes the new selection');
 await setUser(outsider);
 check(!(await roster()).characters.some(c=>c.character_id===other),'Other player sheet absent from selection list');
 await reject(roster('select',other),'42501');
 await reject(roster('attach',other),'42501');
 check((await rpc('pj_sheets','read',{character_id:other},null)).rows.length===0,'Direct identity lookup cannot read another player');
 const patched={...row.sheet_data,fields:{...row.sheet_data.fields,notes:'Player owns the assigned sheet'}};
 row=(await rpc('pj_sheets','upsert',{id:state},{user_id:outsider,character_name:row.character_name,sheet_data:patched,expected_revision:row.revision})).rows[0];
 check(row.sheet_data.fields.notes===patched.fields.notes,'Assigned player manages notes on their own permanent sheet');
 await client.query("select public.df_validate_creation($1,'TEST',$2)",[state,row.revision]);
 row=(await read(state));
 check(row.sheet_data.progression.session.remaining===8,'Attributed PJ starts its own session pool');
 await setUser(uid);
 check(!(await roster()).characters.find(c=>c.character_id===preset).preset,'Claimed preset is no longer unassigned');
 await reject(roster('preset',preset),'42501');
 // Both accounts can claim an unreserved MJ preset, but only the first wins.
 const unreserved=await generated('Roster contested');await roster('preset',unreserved);
 const third=randomUUID();await client.query('insert into auth.users values($1)',[third]);await client.query("insert into public.room_members values('TEST',$1)",[third]);
 const second=engine.getPgClient('creation_test','127.0.0.1');await second.connect();
 try {
  await setUser(outsider);await second.query("select set_config('request.jwt.claim.sub',$1,false)",[third]);
  const attempts=await Promise.allSettled([roster('select',unreserved),second.query("select public.df_character_roster('TEST','select',$1)",[unreserved])]);
  check(attempts.filter(r=>r.status==='fulfilled').length===1,'Concurrent preset attribution has exactly one owner');
 } finally {await second.end();}
 await setUser(uid);
 await roster('dead',preset);
 await reject(roster('offer',preset),'42501');
 await reject(roster('preset',preset),'42501');
 await setUser(outsider);
 check(!(await roster()).characters.some(c=>c.character_id===preset),'Dead PJ excluded from player availability');
 await reject(roster('select',preset),'42501');
 const dead=(await rpc('pj_sheets','read',{id:state},null)).rows[0];
 check(dead.character_status==='dead' && dead.sheet_data.fields.notes===patched.fields.notes,'Dead sheet retains notes and can be read by its owner');
 check(dead.sheet_data.progression.session.closed_at && dead.sheet_data.progression.session.remaining===0 && dead.sheet_data.progression.session.lost===8,'Death closes the pool and forfeits its remainder');
 await reject(rpc('pj_sheets','upsert',{id:state},{user_id:outsider,character_name:dead.character_name,sheet_data:dead.sheet_data,expected_revision:dead.revision}),'42501');
 await reject(client.query("select public.df_progression($1,'TEST','open')",[state]),'42501');
 await reject(client.query("select public.df_validate_creation($1,'TEST',$2)",[state,dead.revision]),'42501');
 await setUser(uid);
 const replacement=await generated('Roster replacement');await roster('preset',replacement,outsider);
 await setUser(outsider);await roster('select',replacement);
 let replacementRow=(await rpc('pj_sheets','read',{user_id:outsider},null)).rows[0];
 await client.query("select public.df_validate_creation($1,'TEST',$2)",[replacementRow.id,replacementRow.revision]);
 replacementRow=await read(replacementRow.id);
 check(replacementRow.id!==state && replacementRow.sheet_data.progression.session.remaining===8 && replacementRow.sheet_data.progression.xp_points===0,'Replacement has its own untouched pool and no dead-character XP');
 check((await read(state)).sheet_data.progression.session.lost===8,'Replacement cannot recover the dead character remainder');
 await setUser(uid);
 const before=(await read(state)).sheet_data;
 await client.query(upgrade);
 assert.deepEqual((await read(state)).sheet_data,before);checks();
 function checks(){check(true,'Reapplying roster migration preserves dead character and values');}
 check(!(await client.query("select has_function_privilege('anon','public.df_character_roster(text,text,uuid,uuid)','EXECUTE') allowed")).rows[0].allowed,'Anonymous roster access refused');
 check(!(await client.query("select has_table_privilege('authenticated','diceforge_v2.character_roster','UPDATE') allowed")).rows[0].allowed,'Direct availability changes denied');
 check((await client.query('select count(*) n from diceforge_v2.character_lifecycle_events where character_id=$1',[preset])).rows[0].n>=5,'Lifecycle retains attribution and death history');
}
