const { readFileSync } = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const read = file => readFileSync(path.join(__dirname, '../js', file), 'utf8');
const context = vm.createContext({});
vm.runInContext(`(()=>{${read('pj-magic.js').replaceAll('export function','function')};this.spellScore=spellScore;})()`,context);
vm.runInContext(read('brp-skills.js').replaceAll('export const', 'const') + '\n' + read('mj-room-data.js').replace(/^import .*;\r?\n/gm, '').replaceAll('export function', 'function') + '\nthis.merge = mergeRoomSheets;', context);
const skills = [];
skills[10] = { score: '45' }; skills[48] = { score: '70' }; skills[14] = { score: '0' };
const row = { id: 1, room_code: 'ABCD', player_name: 'Joueur', sheet_data: { fields: { name: 'Aëlin', profession: 'Mage', motivation: 'Explorer' }, stats: { constitution: 11, taille: 12 }, skills } };
let result = context.merge([], [row], 'ABCD');
assert.equal(result[0].hpMax, '12');
assert.equal(result[0].defense, 'Défense : 45 %');
assert.equal(result[0].deception, 'Baratin : 0 %');
assert.equal(result[0].hp, undefined);
row.sheet_data.stats.intelligence=18;row.sheet_data.spells=[{name:'Feu',points:32,allocation:{score:32,xp_points:0}}];
result=context.merge(result,[row],'ABCD');assert.equal(result[0].spells,'Feu : 32 %');
result[0].secret = 'Secret MJ'; result[0].hp = '0'; result[0].motivation = '';
row.sheet_data.fields.name = 'Nouveau nom'; row.sheet_data.fields.motivation = 'Voyager';
result = context.merge(result, [row], 'ABCD');
assert.equal(result.length, 1);
assert.equal(result[0].name, 'Nouveau nom');
assert.equal(result[0].secret, 'Secret MJ');
assert.equal(result[0].hp, '0');
assert.equal(result[0].motivation, '');
assert.equal(context.merge([], [row], 'WXYZ').length, 0);
assert.equal(context.merge(result, [], 'ABCD').length, 1);
assert.equal(context.merge([{ name: 'Manuel' }], [row], 'ABCD').length, 2);
row.character_id='identity-1';
result=context.merge(result,[row],'ABCD');
const deleted=context.merge(result,[row],'ABCD',{deletedCharacters:[{character_id:'identity-1',state_id:1}]});
assert.equal(deleted[0].sourceDeleted,'yes','A deleted online character is hidden even if a stale row is returned');
assert.equal(deleted[0].secret,'Secret MJ','Local GM notes retained in trash');
const restored=context.merge(deleted,[row],'ABCD');
assert.equal(restored[0].sourceDeleted,'');
assert.equal(restored[0].sourceCharacter,'identity-1');
assert.equal(restored[0].secret,'Secret MJ','Restoration recovers local GM notes');
const fullRestored=context.merge([...Array.from({length:100},()=>({})),...deleted],[row],'ABCD');
assert.equal(fullRestored.length,101,'Restoring saved notes at capacity does not discard them');
assert.equal(fullRestored[100].secret,'Secret MJ');
assert.equal(context.merge([{name:'Homonyme',sourceId:'2',sourceRoom:'ABCD'}],[], 'ABCD',{deletedCharacters:[{character_id:'identity-1',state_id:1}]} )[0].sourceDeleted,undefined,'Name cannot identify a deleted character');
assert.throws(() => context.merge(Array.from({ length: 100 }, () => ({})), [row], 'ABCD'), /100 PJ/);
console.log('Room mapping: BRP scores/HP, idempotent refresh, GM notes and cleared overrides, room isolation, missing sheets and capacity passed.');
