const assert = require('node:assert/strict');
const fs = require('node:fs');
const moduleFile = name => import('data:text/javascript;base64,' + Buffer.from(fs.readFileSync(`js/${name}`, 'utf8')).toString('base64'));
(async () => {
  const { inventoryJournal, inventoryChanges, applyInventoryChanges } = await moduleFile('inventory-sync.js');
  const { characteristicErrors, normalizeCharacteristics, archiveInactiveSkills, transferSheetData } = await moduleFile('sheet-validation.js');
  const values = new Map();
  const storage = { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value) };
  const original = { wallet: { po: 1 }, weapons: [{ id: 'server', name: 'Dague', description: '' }], equipment: [] };
  const first = { ...original, wallet: { po: 2 } };
  const second = { ...first, wallet: { po: 3 } };
  let journal = inventoryJournal(storage, 'room');
  journal.record(original, first); journal.record(first, second);
  journal = inventoryJournal(storage, 'room');
  assert.equal(journal.pending().length, 2, 'Pending edits survive a reload');
  assert.deepEqual(journal.replay(original), second, 'Edits made during load are replayed');
  let cloud = { ...original, equipment: [{ name: 'Sac' }] }, revision = 1;
  const writes = [];
  await assert.rejects(journal.flush(async () => ({ data: cloud, revision }), async () => { throw Error('offline'); }), /offline/);
  assert.equal(journal.pending().length, 2, 'A failed head retains all later edits');
  let release;
  const blocked = new Promise(resolve => { release = resolve; });
  const sending = journal.flush(async () => ({ data: cloud, revision }), async (data, latest) => {
    if (!writes.length) await blocked;
    assert.equal(latest.revision, revision);
    cloud = data; revision++; writes.push(data.wallet.po); return { revision };
  });
  const same = journal.flush(() => { throw Error('Parallel reader'); }, () => {});
  assert.equal(same, sending, 'Only one drain runs at a time');
  journal.record(second, { ...second, wallet: { po: 4 } });
  release(); await sending;
  assert.deepEqual(writes, [2, 3, 4], 'Edits added during an in-flight save remain FIFO');
  assert.equal(cloud.equipment[0].name, 'Sac', 'Unrelated remote edits survive');
  assert.equal(journal.pending().length, 0);
  assert.equal(journal.history().length, 3);
  assert(journal.history().every(entry => entry.status === 'saved' && entry.savedAt));
  journal.record(cloud, { ...cloud, wallet: { po: 5 } });
  cloud = { ...cloud, wallet: { po: 9 } };
  await assert.rejects(journal.flush(async () => ({ data: cloud, revision }), () => { throw Error('Must not write conflict'); }), /Conflit/);
  assert.equal(journal.pending().length, 1, 'Same-field conflicts keep their local history');
  journal.rebase(cloud);
  await journal.flush(async () => ({ data: cloud, revision }), async data => { cloud = data; return { revision: ++revision }; });
  assert.equal(cloud.wallet.po, 5, 'Explicit conflict resolution applies the selected local changes');
  assert(journal.history().at(-1).originalChanges && journal.history().at(-1).rebasedAt, 'Original conflict stays auditable');
  const retry = inventoryJournal(storage, 'retry');
  retry.record(original, first);
  let attempts = 0;
  await retry.flush(async () => ({ data: original, revision: 2 }), async () => {
    if (++attempts === 1) throw { code: '40001' };
    return { revision: 3 };
  });
  assert.equal(attempts, 2);
  assert.deepEqual(inventoryChanges({ items: [{ name: 'A' }] }, { items: [{ id: 'assigned', name: 'A' }] }), []);
  const patch = inventoryChanges({ items: [{ name: 'A' }] }, { items: [{ name: 'B' }] });
  assert.equal(applyInventoryChanges({ items: [{ id: 'assigned', name: 'A' }] }, patch).items[0].name, 'B');
  assert.deepEqual(characteristicErrors({ force: '', intelligence: null, apparence: '999' }), []);
  assert.equal(characteristicErrors({ force: '1.5', taille: '-1', pouvoir: '1000', dexterite: 'abc' }).length, 4);
  assert.deepEqual(normalizeCharacteristics({ force: '', taille: '0012', intelligence: '1e2' }), { force: null, taille: 12, intelligence: 100 });
  const source = { character_id: 'source-character', state_id: 'source-state', campaign_id: 'source-campaign', revision: 50, stats: { force: '12' } };
  const destination = { sheet_data: { character_id: 'target-character', state_id: 'target-state', campaign_id: 'target-campaign', revision: 7 } };
  assert.equal(transferSheetData(source, destination).revision, 7);
  assert.equal(transferSheetData(source, destination).state_id, 'target-state');
  assert.equal(transferSheetData(source, null).revision, undefined);
  assert.equal(source.revision, 50, 'Transfer does not mutate the source');
  const archived = archiveInactiveSkills({ skills: [{ id: 'active', points: 2 }, { id: 'unused', points: 17 }], retiredSkills: { older: { points: 8 } } }, [0], []);
  assert.equal(archived.unused.points, 17); assert.equal(archived.older.points, 8); assert.equal(archived.active, undefined);
  console.log('Sauvegardes : FIFO persistante, reprise, chargement, conflits, N/A, archives et transfert validés.');
})().catch(error => { console.error(error); process.exitCode = 1; });
