import assert from 'node:assert/strict';
import { creationBudget, creationBudgetErrors, creationValidationErrors } from '../js/creation-budget.js';
const draft={creation:{phase:'draft'},fields:{profession:'Guerrier',skillProfessionalPool:'325'},stats:{intelligence:12}};
const skill=(name,points)=>({name,points});
const invalid=[skill('Arme de mêlée (Épée)',109),skill('Estimation',387)];
const broken=creationBudget(draft,invalid,[]);
assert.equal(broken.remaining,-51);
assert.equal(broken.professionalRemaining,216);
assert.equal(broken.personalRemaining,-267);
assert.equal(creationBudgetErrors(draft,invalid,[]).length,2);
assert.equal(creationBudgetErrors(draft,[skill('Arme de mêlée (Épée)',0),skill('Estimation',121)],[]).length,1,'Unused professional points cannot pay for outside skills');
let budget=creationBudget(draft,[skill('Arme de mêlée (Épée)',350),skill('Estimation',50)],[]);
assert.equal(budget.professionalRemaining,0);
assert.equal(budget.personalRemaining,45,'Personal points also supplement professional skills');
assert.deepEqual(creationBudgetErrors(draft,[skill('Arme de mêlée (Épée)',325),skill('Estimation',120)],[]),[]);
assert.equal(creationBudget(draft,[skill('Estimation',90)],[{name:'Feu',points:40}]).personalRemaining,-10,'Nonmagical spell and skill allocations share personal points');
const mage={...draft,fields:{...draft.fields,profession:'Sorcier'}};
assert.equal(creationBudget(mage,[],[{name:'Feu',points:80}]).professionalRemaining,245,'Magical profession may spend professional points on spells');
const locked={...mage,creation:{phase:'play',professional:325,personal:120},stats:{intelligence:20}};
budget=creationBudget(locked,[{name:'Estimation',points:35,allocation:{origin:'creation',creation_points:25,xp_points:10}}],[{name:'Feu',points:32,allocation:{origin:'learning',learning_points:32}}]);
assert.equal(budget.spent,25,'XP and newly learned spells do not consume the creation budget');
assert.equal(budget.personal,120,'Initial personal pool stays fixed after play begins');
assert.deepEqual(creationBudgetErrors(locked,invalid,[]),[],'Historical locked sheet is not rewritten or blocked by draft controls');
console.log('PASS creation budget: actual -51/-267 case, separate pools, shared skills/spells, and acquired points.');
const unfinished=[skill('Arme de mêlée (Épée)',325),skill('Estimation',10)];
assert.deepEqual(creationBudgetErrors(draft,unfinished,[]),[],'110 remaining points can be saved in a draft');
assert.match(creationValidationErrors(draft,unfinished,[]).join(' '),/110 point/,'110 remaining points prevent validation');
assert.match(creationValidationErrors(draft,[skill('Arme de mêlée (Épée)',325),skill('Estimation',119)],[]).join(' '),/1 point/,'Even one remaining point prevents validation');
assert.deepEqual(creationValidationErrors(draft,[skill('Arme de mêlée (Épée)',325),skill('Estimation',120)],[]),[]);
assert.deepEqual(creationValidationErrors(locked,unfinished,[]),[],'Existing validated sheets remain unchanged and usable');
console.log('PASS complete creation: draft saves allowed, 110/1 unspent points block validation, exact allocation allowed, old sheets preserved.');
