const { readFileSync } = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const read = file => readFileSync(path.join(__dirname, '../js', file), 'utf8');
const context = vm.createContext({});
vm.runInContext(`(()=>{${read('pj-magic.js').replaceAll('export function','function')};this.spellScore=spellScore;})()`,context);
vm.runInContext(read('brp-skills.js').replaceAll('export const', 'const') + '\n' + read('mj-room-data.js').replace(/^import .*;\r?\n/gm, '').replaceAll('export function', 'function') + '\nthis.merge = mergeRoomSheets;', context);
const skills = [];
skills[10] = { score: '45' }; skills[48] = { score: '70' }; skills[14] = { score: '0' };
const row = { id: 1, room_code: 'ABCD', player_name: 'Joueur', sheet_data: { fields: { name: 'Aëlin', profession: 'Mage', motivation: 'Explorer' }, stats: { constitution: 11, taille: 12 }, skills } };
let result = context.merge([], [row], 'ABCD');
assert.equal(result[0].hpMax, '12');
assert.equal(result[0].defense, 'Défense : 45 %');
assert.equal(result[0].deception, 'Baratin : 0 %');
assert.equal(result[0].hp, undefined);
row.sheet_data.stats.intelligence=18;row.sheet_data.spells=[{name:'Feu',points:32,allocation:{score:32,xp_points:0}}];
result=context.merge(result,[row],'ABCD');assert.equal(result[0].spells,'Feu : 32 %');
result[0].secret = 'Secret MJ'; result[0].hp = '0'; result[0].motivation = '';
row.sheet_data.fields.name = 'Nouveau nom'; row.sheet_data.fields.motivation = 'Voyager';
result = context.merge(result, [row], 'ABCD');
assert.equal(result.length, 1);
assert.equal(result[0].name, 'Nouveau nom');
assert.equal(result[0].secret, 'Secret MJ');
assert.equal(result[0].hp, '0');
assert.equal(result[0].motivation, '');
assert.equal(context.merge([], [row], 'WXYZ').length, 0);
assert.equal(context.merge(result, [], 'ABCD').length, 1);
assert.equal(context.merge([{ name: 'Manuel' }], [row], 'ABCD').length, 2);
row.character_id='identity-1';
result=context.merge(result,[row],'ABCD');
const deleted=context.merge(result,[row],'ABCD',{deletedCharacters:[{character_id:'identity-1',state_id:1}]});
assert.equal(deleted[0].sourceDeleted,'yes','A deleted online character is hidden even if a stale row is returned');
assert.equal(deleted[0].secret,'Secret MJ','Local GM notes retained in trash');
const restored=context.merge(deleted,[row],'ABCD');
assert.equal(restored[0].sourceDeleted,'');
assert.equal(restored[0].sourceCharacter,'identity-1');
assert.equal(restored[0].secret,'Secret MJ','Restoration recovers local GM notes');
const fullRestored=context.merge([...Array.from({length:100},()=>({})),...deleted],[row],'ABCD');
assert.equal(fullRestored.length,101,'Restoring saved notes at capacity does not discard them');
assert.equal(fullRestored[100].secret,'Secret MJ');
assert.equal(context.merge([{name:'Homonyme',sourceId:'2',sourceRoom:'ABCD'}],[], 'ABCD',{deletedCharacters:[{character_id:'identity-1',state_id:1}]} )[0].sourceDeleted,undefined,'Name cannot identify a deleted character');
assert.throws(() => context.merge(Array.from({ length: 100 }, () => ({})), [row], 'ABCD'), /100 PJ/);
const canonical={...row,id:'state-new',character_id:'same-hero'};
const sources=[{state_id:'state-new',character_id:'same-hero',legacy_sheet_ids:['85']}];
const oldSummary=context.sheetSummary(canonical);
const originalNotes=[
 {name:'Nouveau nom',sourceRoom:'ABCD',sourceId:'85',sourceSnapshot:JSON.stringify(oldSummary),secret:'Ancien secret',hp:'0',motivation:''},
 {name:'Nouveau nom',sourceRoom:'ABCD',sourceId:'state-new',sourceCharacter:'same-hero',sourceSnapshot:JSON.stringify(oldSummary),secret:'Secret plus récent',npc:'Contact conservé',hp:'5'}
];
const clean=context.merge(originalNotes,[canonical],'ABCD',{sheetSources:sources});
assert.equal(clean.length,1,'Legacy integer and permanent campaign identity form one notebook card');
assert.equal(clean[0].sourceId,'state-new');
assert.equal(clean[0].sourceCharacter,'same-hero');
assert.equal(clean[0].secret,'Ancien secret');
assert.equal(clean[0].npc,'Contact conservé','Complementary notes are merged');
assert.equal(clean[0].hp,'0','Zero HP survives merging');
assert.equal(clean[0].motivation,'','Deliberately cleared values survive merging');
assert(JSON.parse(clean[0].sourceMergeConflicts).some(n=>n.field==='secret'&&n.value==='Secret plus récent'),'Both conflicting secrets remain available');
assert(JSON.parse(clean[0].sourceMergeConflicts).some(n=>n.field==='hp'&&n.value==='5'),'Conflicting HP remains available');
assert.equal(originalNotes[0].sourceId,'85','Input/backup stays unchanged');
assert.equal(context.merge(clean,[canonical],'ABCD',{sheetSources:sources}).length,1,'Second refresh cannot recreate the duplicate');
assert.equal(context.merge(originalNotes,[],'ABCD',{sheetSources:sources,deletedCharacters:[{state_id:'state-new',character_id:'same-hero'}]})[0].sourceDeleted,'yes','Deletion also hides legacy notes');
assert.equal(context.merge([{name:'Nouveau nom'}],[canonical],'ABCD',{sheetSources:sources}).length,2,'Manual same-name notes are never inferred as the same character');
assert.equal(context.merge([{...originalNotes[0],sourceRoom:'WXYZ'}],[canonical],'ABCD',{sheetSources:sources}).length,2,'Other rooms remain isolated');
assert.equal(context.merge(originalNotes,[],'ABCD',{sheetSources:[...sources,{state_id:'other',character_id:'other',legacy_sheet_ids:['85']}]}).length,2,'Ambiguous legacy identities are not merged');
assert.equal(context.merge([{...originalNotes[0],sourceId:'state-new',sourceCharacter:'same-hero'}, {...originalNotes[1],sourceCharacter:'other-hero'}],[],'ABCD').length,2,'Conflicting permanent identities are never merged');
console.log('Room mapping: BRP scores/HP, idempotent refresh, GM notes and cleared overrides, room isolation, missing sheets and capacity passed.');
