const { readFileSync } = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const read = file => readFileSync(path.join(__dirname, '../js', file), 'utf8');
const context = vm.createContext({});
vm.runInContext(read('brp-skills.js').replaceAll('export const', 'const') + '\n' + read('mj-room-data.js').replace(/^import .*;\r?\n/, '').replaceAll('export function', 'function') + '\nthis.merge = mergeRoomSheets;', context);
const skills = [];
skills[10] = { score: '45' }; skills[48] = { score: '70' }; skills[14] = { score: '0' };
const row = { id: 1, room_code: 'ABCD', player_name: 'Joueur', sheet_data: { fields: { name: 'Aëlin', profession: 'Mage', motivation: 'Explorer' }, stats: { constitution: 11, taille: 12 }, skills } };
let result = context.merge([], [row], 'ABCD');
assert.equal(result[0].hpMax, '12');
assert.equal(result[0].defense, 'Défense : 45 %');
assert.equal(result[0].deception, 'Baratin : 0 %');
assert.equal(result[0].hp, undefined);
result[0].secret = 'Secret MJ'; result[0].hp = '0'; result[0].motivation = '';
row.sheet_data.fields.name = 'Nouveau nom'; row.sheet_data.fields.motivation = 'Voyager';
result = context.merge(result, [row], 'ABCD');
assert.equal(result.length, 1);
assert.equal(result[0].name, 'Nouveau nom');
assert.equal(result[0].secret, 'Secret MJ');
assert.equal(result[0].hp, '0');
assert.equal(result[0].motivation, '');
assert.equal(context.merge([], [row], 'WXYZ').length, 0);
assert.equal(context.merge(result, [], 'ABCD').length, 1);
assert.equal(context.merge([{ name: 'Manuel' }], [row], 'ABCD').length, 2);
assert.throws(() => context.merge(Array.from({ length: 100 }, () => ({})), [row], 'ABCD'), /100 PJ/);
console.log('Room mapping: BRP scores/HP, idempotent refresh, GM notes and cleared overrides, room isolation, missing sheets and capacity passed.');
